# Spring Boot configuration
spring:
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: development
  # Security configuration
  security:
    user:
      name: user
      password: user
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB.HOST}:${DB.PORT}/${DB.NAME}
    username: ${DB.USER}
    password: ${DB.PASSWORD}
#    url: jdbc:postgresql://10.10.10.31:5432/presensi_gs
#    username: postgres
#    password: S@y@Br0nt0
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
# Logger configuration
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework: info
    org.hibernate: debug
# Server configuration
server:
  port: 8000 #set your port